In [1]:
import pandas as pd

In [2]:
df = pd.concat([
    pd.read_csv('Output\Early_Data_Scraped-Raw.csv'),
    pd.read_csv('Output\Early_Data_Scraped-Raw_Backup_01.csv'),
    pd.read_csv('Output\Early_Data_Scraped-Raw_Backup_02.csv')
    ])
df = df.dropna()
df = df.drop_duplicates(subset=('title','price','land','building','location'), keep='last')
df = df.reset_index(drop=True)

In [3]:
df

,title,price,land,building,bed,bath,floor,certificate,location
0,"RUMAH 2 LANTAI MURAH DLM RINGROAD, AREA FAVORI...",Rp 2.000.000.000,130.0,130.0,5,5,2.0,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
1,Rumah mewah dalam perum onegate di Jombor,Rp 2.200.000.000,130.0,130.0,5,5,2.0,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
2,Rumah baru di Jongke dalam cluster perumahan,Rp 1.890.000.000,130.0,130.0,5,5,2.0,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
3,Kode : RSH 3219 #Rumah Bagus Murah Strategis d...,Rp 600.000.000,130.0,90.0,3,2,1.0,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
4,Promo Rumah baru siap huni dalam perum sleman,Rp 395.000.000,110.0,50.0,3,1,0.0,SHM - Sertifikat Hak Milik,"Seyegan, Sleman Kab., Yogyakarta D.I."
...,...,...,...,...,...,...,...,...,...
2868,Jual cepat Rumah dan Gudang murah,Rp 5.300.000.000,677.0,900.0,5,5,3.0,SHM - Sertifikat Hak Milik,"Gondokusuman, Yogyakarta Kota, Yogyakarta D.I."
2869,Rumah Dalam Kota Barat XT Square Dekat Jalan M...,Rp 1.500.000.000,72.0,130.0,3,2,3.0,SHM - Sertifikat Hak Milik,"Umbulharjo, Yogyakarta Kota, Yogyakarta D.I."
2870,Rumah Baru di Area Kampus UNS (Cluster 26 Unit),Rp 485.000.000,83.0,45.0,2,1,1.0,SHM - Sertifikat Hak Milik,"Jebres, Surakarta Kota, Jawa Tengah"
2871,Rumah cluster minimalis modern lingkungan kamp...,Rp 499.000.000,85.0,45.0,2,1,1.0,SHM - Sertifikat Hak Milik,"Grogol, Sukoharjo Kab., Jawa Tengah"
2872,Termurah 400Jt-an: Rumah Full Furnish 15Menit ...,Rp 475.000.000,105.0,50.0,2,1,1.0,SHM - Sertifikat Hak Milik,"Kasihan, Bantul Kab., Yogyakarta D.I."

In [4]:
df.dtypes.info

<bound method Series.info of title           object
price           object
land           float64
building       float64
bed             object
bath            object
floor          float64
certificate     object
location        object
dtype: object>

In [5]:
df = df.astype(str)

In [6]:
cols = ["price","land", "building", "bed", "bath", "floor", "certificate"]
for col in cols :
    df = df[df[f"{col}"].str.contains("&gt;10") == False]

In [7]:
df = df[df['location'].str.contains("Yogyakarta") == True]

In [8]:
conv = {
    'land': float, 
    'building': float,
    'bed': float,
    'bath':float,
    'floor': float
    }

df = df.astype(conv)

In [9]:
conv = {
    'land': int, 
    'building': int,
    'bed': int,
    'bath':int,
    'floor': int
    }

df = df.astype(conv)

In [10]:
df = df[(df['land']>0) == True]

In [11]:
df

,title,price,land,building,bed,bath,floor,certificate,location
0,"RUMAH 2 LANTAI MURAH DLM RINGROAD, AREA FAVORI...",Rp 2.000.000.000,130,130,5,5,2,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
1,Rumah mewah dalam perum onegate di Jombor,Rp 2.200.000.000,130,130,5,5,2,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
2,Rumah baru di Jongke dalam cluster perumahan,Rp 1.890.000.000,130,130,5,5,2,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
3,Kode : RSH 3219 #Rumah Bagus Murah Strategis d...,Rp 600.000.000,130,90,3,2,1,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
4,Promo Rumah baru siap huni dalam perum sleman,Rp 395.000.000,110,50,3,1,0,SHM - Sertifikat Hak Milik,"Seyegan, Sleman Kab., Yogyakarta D.I."
...,...,...,...,...,...,...,...,...,...
2866,Rumah minimalis siap huni di dkt pasar cebongan,Rp 625.000.000,108,60,2,1,1,SHM - Sertifikat Hak Milik,"Mlati, Sleman Kab., Yogyakarta D.I."
2867,rumah cantik &amp; kos2an dekat univ aisyiah j...,Rp 1.300.000.000,77,150,3,2,2,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
2868,Jual cepat Rumah dan Gudang murah,Rp 5.300.000.000,677,900,5,5,3,SHM - Sertifikat Hak Milik,"Gondokusuman, Yogyakarta Kota, Yogyakarta D.I."
2869,Rumah Dalam Kota Barat XT Square Dekat Jalan M...,Rp 1.500.000.000,72,130,3,2,3,SHM - Sertifikat Hak Milik,"Umbulharjo, Yogyakarta Kota, Yogyakarta D.I."
2872,Termurah 400Jt-an: Rumah Full Furnish 15Menit ...,Rp 475.000.000,105,50,2,1,1,SHM - Sertifikat Hak Milik,"Kasihan, Bantul Kab., Yogyakarta D.I."

In [13]:
df.price = df.price.str.replace(r'\D+', '', regex=True)
df.price = df.price.astype('float')
df.price = df.price.astype('int64')

In [15]:
df.reset_index(inplace=True, drop=True)

In [16]:
df

,title,price,land,building,bed,bath,floor,certificate,location
0,"RUMAH 2 LANTAI MURAH DLM RINGROAD, AREA FAVORI...",2000000000,130,130,5,5,2,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
1,Rumah mewah dalam perum onegate di Jombor,2200000000,130,130,5,5,2,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
2,Rumah baru di Jongke dalam cluster perumahan,1890000000,130,130,5,5,2,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
3,Kode : RSH 3219 #Rumah Bagus Murah Strategis d...,600000000,130,90,3,2,1,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
4,Promo Rumah baru siap huni dalam perum sleman,395000000,110,50,3,1,0,SHM - Sertifikat Hak Milik,"Seyegan, Sleman Kab., Yogyakarta D.I."
...,...,...,...,...,...,...,...,...,...
2779,Rumah minimalis siap huni di dkt pasar cebongan,625000000,108,60,2,1,1,SHM - Sertifikat Hak Milik,"Mlati, Sleman Kab., Yogyakarta D.I."
2780,rumah cantik &amp; kos2an dekat univ aisyiah j...,1300000000,77,150,3,2,2,SHM - Sertifikat Hak Milik,"Sleman, Sleman Kab., Yogyakarta D.I."
2781,Jual cepat Rumah dan Gudang murah,5300000000,677,900,5,5,3,SHM - Sertifikat Hak Milik,"Gondokusuman, Yogyakarta Kota, Yogyakarta D.I."
2782,Rumah Dalam Kota Barat XT Square Dekat Jalan M...,1500000000,72,130,3,2,3,SHM - Sertifikat Hak Milik,"Umbulharjo, Yogyakarta Kota, Yogyakarta D.I."
2783,Termurah 400Jt-an: Rumah Full Furnish 15Menit ...,475000000,105,50,2,1,1,SHM - Sertifikat Hak Milik,"Kasihan, Bantul Kab., Yogyakarta D.I."

In [17]:
df.to_csv('Output\Mid_01_Data_Cleaned.csv', index=False)